version: '3.8'

services:
  # Backend API service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=167.71.194.1
      - DATABASE_URL=mysql://root:StrongProductionPassword@mysql:3306/tourism_db
      - JWT_SECRET=production_jwt_secret_key_should_be_long_and_complex
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
    restart: unless-stopped
    volumes:
      - ./public:/app/public
    networks:
      - tourism-network

  # MySQL database service
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=StrongProductionPassword
      - MYSQL_DATABASE=tourism_db
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - tourism-network

volumes:
  mysql-data:

networks:
  tourism-network:
    driver: bridge
